/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    DefaultLayout: typeof import('./src/components/layouts/DefaultLayout.vue')['default']
    ExplainItem: typeof import('./src/components/game/ExplainItem.vue')['default']
    GameLayout: typeof import('./src/components/layouts/GameLayout.vue')['default']
    Header: typeof import('./src/components/containers/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Summary: typeof import('./src/components/game/Summary.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
